### ISSUE TITLE
Get header block size without encoding?

### ISSUE THREAD

**Issue by DaanDeMeyer** [litespeedtech/ls-qpack#25]
Is there a function in ls-qpack to get the header block size without doing the actual encoding? Without knowing the header block size, I can't know the offset at which the header block starts since the offset is dependent on the header block size which is encoded as a varint.

I can get around this by encoding to a temporary buffer and copying to the correct offset after encoding the size but this seems wasteful. I'd rather encode directly to the final buffer.

**Comment by dtikhonov** [comment]
There is no function to do this -- but it can be implemented.

Calculating the header block size before encoding is likely even more wasteful, as it's an expensive operation.  For one thing, the state of the dynamic table may change while a header block is being encoded.

If you want to write directly to the destination buffer, one way to do it is to guess the size and then `memmove()` in case of an error.  Or pad the size of the varint.

**Comment by DaanDeMeyer** [comment]
I'll give the `memmove` approach a try. Thanks for the quick response.
