### ISSUE TITLE
Decoder breaks if "Set Dynamic Table Capacity" instruction doesn't match its initial capacity

### ISSUE THREAD

**Issue by guoye-zhang** [litespeedtech/ls-qpack#44]
If the other side chooses a smaller dynamic table size than what we initialized the decoder with, decoding headers will fail or get corrupted.

We think it’s because `qpd_max_entries` isn’t updated in `qdec_update_max_capacity`.

Reproducing project attached: [qpack_bug_repro.zip](https://github.com/litespeedtech/ls-qpack/files/9637094/qpack_bug_repro.zip) If you increase the initial dynamic table capacity by even 1 from 16383 to 16384, decoding starts failing.

**Comment by litespeedtech** [comment]
Thank, we will add it as a test case. 
The fix to this particular case is easy, like you said, just update `qpd_max_entries` accordingly.
However, more complicate logic is related to `qpd_max_entries` and `qpd_largest_known_id`, those also need to be updated, I believe.  RFC allows changing dynamic table size up and down at anytime, make it more tricky. may need bigger change to get it right.

**Comment by litespeedtech** [comment]
Please check the fix.

**Comment by guoye-zhang** [comment]
Looks good, thanks!

**Comment by dtikhonov** [comment]
> If the other side chooses a smaller dynamic table size than what we initialized the decoder with, decoding headers will fail or get corrupted.

This is incorrect.  The value of `MaxTableCapacity` and, therefore, `MaxEntries`, never changes after being set initially.  See the RFC.

In the attached test case, when you change the initial table size when initializing the decoder, you effectively lie to the decoder about the table size used by the encoder.  This causes them to disagree about entry IDs.

**Comment by guoye-zhang** [comment]
The decoder is created with the max size we advertise in SETTINGS, and the peer can choose any size which is smaller right? We don't know what the table size the peer encoder will be using when creating the decoder.

**Comment by dtikhonov** [comment]
There are two sizes: maximum and dynamic.  The former is used to calculate MaxEntries and is set just once.  The latter can vary.  If  MaxEntries could change, the protocol would not work.

**Comment by dtikhonov** [comment]
Reverted in #83 (v2.6.3)

**Comment by guoye-zhang** [comment]
OK got it. We were advertising a smaller value in SETTINGS than the value used when initializing the decoder a few years ago so that was the bug.
