### ISSUE TITLE
Document outdated: `lsqpack_dec_destroy_header_list()` was removed

### ISSUE THREAD

**Issue by unasuke** [litespeedtech/ls-qpack#48]
The function `lsqpack_dec_destroy_header_list()` referenced here is removed at v2.0.0 (6062085)

https://github.com/litespeedtech/ls-qpack/blob/bbd707065f4547a1b5a25bbc1cf6c1963e86b8cf/lsqpack.h#L340-L346

What is the new API insterad of `lsqpack_dec_destroy_header_list()`?

**Comment by litespeedtech** [comment]
The outdated document has been fixed.
Due to API change, header_list no longer exist or managed by ls-qpack library. Caller need to manage provided memory buffer.
