### ISSUE TITLE
Missing Install target

### ISSUE THREAD

**Issue by Hellseher** [litespeedtech/ls-qpack#52]
Hi,

I try to figure out how to install the library in traditional *nix (unix, linux) way to `bin`, `include` and `lib` directories. It looks like generated makefiles missed that target.

UP.

I see this PR was merged #50, but it's failed to find the target.
```
make: *** No rule to make target 'install'.  Stop.
```
ls-qpack: v2.5.3

Thanks,
Oleg

**Comment by litespeedtech** [comment]
If you create a `build` directory, compile there, then you need to run `make install` under that directory.
